BOOK_NAME_ARRAY DB "To Kill a Mockingbird$", 8 DUP('$')
	    DB "1984$", 25 DUP('$')
	    DB "Pride and Prejudice$", 10 DUP('$')
	    DB "The Great Gatsby$", 13 DUP('$')
	    DB "Moby - Dick$", 18 DUP('$')
	    DB "The Catcher in the Rye$", 7 DUP('$')
	    DB "The Lord of the Rings$", 8 DUP('$')
	    DB "The Alchemist$", 16 DUP('$')
	    DB "Sapiens$", 22 DUP('$')
	    DB "The Da Vinci Code$", 12 DUP('$')
        DB "War and Peace$", 16 DUP('$')
        DB "Brave New World$", 14 DUP('$')
        DB "The Hobbit$", 19 DUP('$')
        DB "Crime and Punishment$", 9 DUP('$')
        DB "The Picture of Dorian Gray$", 3 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
	;Author
	BOOK_AUTHORS DB "Harper Lee$", 19 DUP('$')
	    DB "George Orwell$", 16 DUP('$')
	    DB "Jane Austen$", 18 DUP('$')
	    DB "F. Scott Fitzgerald$", 10 DUP('$')
	    DB "Herman Melville$", 14 DUP('$')
	    DB "J.D. Salinger$", 16 DUP('$')
	    DB "J.R.R. Tolkien$", 15 DUP('$')
	    DB "Paulo Coelho$", 17 DUP('$')
	    DB "Yuval Noah Harari$", 12 DUP('$')
	    DB "Dan Brown$", 20 DUP('$')
        DB "Leo Tolstoy$", 18 DUP('$')
        DB "Aldous Huxley$", 16 DUP('$')
        DB "J.R.R. Tolkien$", 15 DUP('$')
        DB "Fyodor Dostoevsky$", 11 DUP('$')
        DB "Oscar Wilde$", 18 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')
        DB 30 DUP('$')

    ;User Details
    USER_ID_ARRAY DB "ALI_BABA$", 31 DUP('$')
        DB "THE_BEST_DOGGAN$", 24 DUP('$')
        DB "ABG_CHIN$", 31 DUP('$')
        DB "SAMSAM_CLOWN$", 27 DUP('$')
        DB "CSTANTAN$", 31 DUP('$')
        DB "LEONGYY$", 32 DUP('$')
        DB "LIM_ZHI_PING$", 27 DUP('$')
        DB "G.E.M.$", 33 DUP('$')
        DB "JAY_CHOU$", 31 DUP('$')
        DB "COLDPLAY$", 31 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')

    
    USER_PASSWORD_ARRAY DB "12345678910$"
        DB "12345$" 6 DUP('$')
        DB "ezpass$" 5 DUP('$')
        DB "password$" 3 DUP('$')
        DB "user1234$" 3 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')
        DB 12 DUP('$')

    RET_DATE_ARRAY DB 11 DUP("$")
                    DB "05/09/2024$"
                    DB "03/05/2024$"
                    DB 11 DUP("$")
                    DB "24/08/2024$"
                    DB 11 DUP("$")
                    DB "07/06/2024$"
                    DB 11 DUP("$") 
                    DB 11 DUP("$")
                    DB "10/09/2024$"
                    DB 11 DUP("$")
                    DB 11 DUP("$")
                    DB 11 DUP("$")
                    DB "11/08/2024$"
                    DB 11 DUP("$")
                    DB 11 DUP("$")
                    DB 11 DUP("$")
                    DB 11 DUP("$")
                    DB 11 DUP("$")
                    DB 11 DUP("$")    
     ;Borrow Status
    BORROW_BY_ARRAY DB 40 DUP("$")
        DB "CSTAN$", 34 DUP('$');
        DB "LIM_ZHI_PING$", 27 DUP('$');
        DB 40 DUP("$")
        DB "SAMSAM_CLOWN$", 27 DUP('$');
        DB 40 DUP("$")
        DB "THE_BEST_DOGGAN$", 24 DUP('$');
        DB 40 DUP("$")
        DB 40 DUP("$")
        DB "ABG_CHIN$", 31 DUP('$');
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB "LEONGYY$", 32 DUP('$');
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')
        DB 40 DUP('$')